sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 295456
  alioss:
    access-key-id: LTAI5tJr8bhLfrnnSExaRzij
    endpoint: oss-cn-hangzhou.aliyuncs.com
    bucket-name: wzy-sky-takeaway
    access-key-secret: qYGErcysNJ0QrMPEdQXADtyXUN2joX
