sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 295456
  alioss:
    access-key-id: ****************
    endpoint: *************
    bucket-name: ***********
    access-key-secret: *******************
  redis:
    host: 192.168.163.128
    port: 6379
    password: 295456
  wechat:
    appid: *************
    secret: ****************

  shop:
    address: 淮南市田家庵区安徽理工大学

  baidu:
    ak: *********************
#    mchid:
#    mchSerialNo:
#    privateKeyFilePath:
#    apiV3Key:
#    weChatPayCertFilePath:
#    notifyUrl:
#    refundNotifyUrl:
