sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 295456
  alioss:
    access-key-id: LTAI5tJr8bhLfrnnSExaRzij
    endpoint: oss-cn-hangzhou.aliyuncs.com
    bucket-name: wzy-sky-takeaway
    access-key-secret: qYGErcysNJ0QrMPEdQXADtyXUN2joX
  redis:
    host: 192.168.163.128
    port: 6379
    password: 295456
  wechat:
    appid: wx34addf843a6b8f31
    secret: 1564794135698bbf5d6fbf28afb827dc

  shop:
    address: 淮南市田家庵区安徽理工大学

  baidu:
    ak: **************************
#    mchid:
#    mchSerialNo:
#    privateKeyFilePath:
#    apiV3Key:
#    weChatPayCertFilePath:
#    notifyUrl:
#    refundNotifyUrl:
